[package]
name = "napi"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
napi-sys = { "path" = "../napi-sys" }


[lib]
crate-type = ["cdylib"]
